
#####################################################################################
# Global variables
project_git_url: &__PROJECT_GIT_URL__ https://github.com/guilhermedimarchi/concourse-demo
master_branch: &__master_branch__ master
#####################################################################################

resources:
- name: java-source-master
  type: git
  source:
    uri: *__PROJECT_GIT_URL__
    branch: *__master_branch__

jobs:
- name: Run-automatically
  plan:
  - get: java-source-master
    trigger: true
  - task: simple-console-log
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This job is automatically triggered upon any version change in the resource."
