
#####################################################################################
# Global variables
project_git_url: &__PROJECT_GIT_URL__ https://github.com/guilhermedimarchi/concourse-demo
ci_git_url: &__CI_GIT_URL__ https://github.com/guilhermedimarchi/concourse-ci
master_branch: &__master_branch__ master
#####################################################################################

resources:
- name: java-source-master
  type: git
  source:
    uri: *__PROJECT_GIT_URL__
    branch: *__master_branch__

- name: ci-source
  type: git
  source:
    uri: *__CI_GIT_URL__
    branch: master

jobs:
- name: Build
  plan:
  - get: java-source-master
    trigger: true
  - task: build-and-unit-test
    file: ci-source/tasks/build-java.yml
    input_mapping:
      java-source: java-source-master
      ci-source: ci-source
    output_mapping:
      build-output: build-output

